CREATE TABLE P_USERS
(
    id INTEGER NOT NULL PRIMARY KEY,
    USER_NAME VARCHAR(100) NOT NULL,
    GROUP_ID INTEGER NOT NULL
);

CREATE TABLE P_GROUPS
(
    id INTEGER NOT NULL PRIMARY KEY,
    GROUP_NAME VARCHAR(100) NOT NULL
);

CREATE TABLE OFFICES
(
    id INTEGER NOT NULL PRIMARY KEY,
    listname_id INTEGER NOT NULL
);

CREATE TABLE SUBSCRIPTIONSTYPE
(
    id INTEGER NOT NULL PRIMARY KEY,
    SUBSCRIPTIONTYPE VARCHAR(100) NOT NULL
);

CREATE TABLE SUBSCRIPTIONS
(
    id INTEGER NOT NULL PRIMARY KEY,
    SUBSCRIPTIONSTYPE_ID INTEGER NOT NULL,
    OFFICE_ID INTEGER NOT NULL
);

CREATE TABLE P_STATEMENT_BASE_TYPE
(
    id INTEGER NOT NULL PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL
);

CREATE TABLE P_STATEMENT_BASE
(
    id INTEGER NOT NULL PRIMARY KEY,
    LISTNAME_ID INTEGER NOT NULL,
    STATEMENT_BASE_TYPE_ID INTEGER NOT NULL,
    LIMIT INTEGER NOT NULL,
    START_DATE DATE NOT NULL,
    FINISH_DATE DATE NOT NULL
);

CREATE SEQUENCE generator_P_STATEMENT_BASE START WITH 20 INCREMENT BY 1;

CREATE TABLE P_STATEMENT
(
    id INTEGER NOT NULL PRIMARY KEY,
    STATEMENT_BASE_ID INTEGER NOT NULL,
    STATEMENT_COUNT INTEGER NOT NULL,
    STATEMENT_ARITHMETIC_TYPE VARCHAR(20) NOT NULL,
    PHONE VARCHAR(20) NOT NULL,
    STATEMENT_DATE DATE NOT NULL,
    USER_ID INTEGER NOT NULL
);